language: node_js
node_js:
  - "5.0"
notifications:
  slack: devops-training-spb:0G7208FSSrpINrw8RCctGRpw
services:
  - postgresql
before_script:
  - createuser -s crudtest
  - psql -c 'create database crudtest;' -U crudtest
addons:
  postgresql: "9.4"
