language: node_js

services:
 - postgresql
node_js: 
 - "5.10.1"
addons:
  postgresql: "9.4"
before_script:
 - bash install.sh
script:
 - source env.sh && npm run test
notifications:
  slack: devops-training-spb:0G7208FSSrpINrw8RCctGRpw
deploy:
  api_key:
    secure: CWLqzzFLNYypXnBTqfsArLWKEQmbRco81ZFKtD2mH/4zZp12SXPiY1qCvQqBw3bQApbQucGFmq71BCP9rHB/1TOFwbYLX3VPmhm+D+XJbJGUHNp41n5+sxcFMzU6khHP1HP+KZWnyYmsdmFkBNH1zPsdxQHewZT8WnEdW7QpxqZOwVS9DEg7eQiRzKCIxkE+jkROw/5tZ4/bCdYvqelqH15M/0Rl5DDWzO0OQs+UDTed8bRwThyee80IyHQJT5LwfS/LHtMoKPhusCWYWOa99c7J8lQ9IT+W19G18Pw1gt+4MlHqNLjLZoQ7PmUQQuojVEBB6yonu6m8z15UdxAjZpjqel1QYrQIKu1akXPhvMa1Sudp5b1AzGRPsIRXhkry6w0zzkeOrkciVoliDrula4m38mhL54mSYleKezjekLeP9g488Hrt9t8TjcX/1iHtVthpOI5w8eD+HxepXDqwMkh0UoyDlRy1dItTdthJN1g7f2tglmHabAvpIhl3u4hpKGBL5pzTrs1MDdOMWmCSXnlYsywW2ugWg9oheLLOn1SankSuuAmwdzabYq5mddLXFPinI6trOaX8BzdgEaXSyWw0c1vE6hYSLWASaPialric2Qq+Zs0w5RHOa2G/OaMzb3LIgBuEIUrto/7wcvXJifI4/hjj3oJ0Y2r+dqUSpj8=
